### ISSUE TITLE
Errata lettura stato centrale quando armata/disarmata con radiochiave.

### ISSUE THREAD

**Issue by antonioromito** [lcavalli/esp-kyo-alarm-generic#5]
Armando/Disarmando via HA lo stato della centrale viene letto correttamente ed aggiornato in maniera congruente. 
Provando ad armare la centrale con radiochiave ho notato che lo stato della centrale su HA rimane sempre disarmato come se non leggesse l'aggiornamento di stato correttamente.
Stessa cosa se armo da HA e disarmo la centrale con radiochiave, lo stato risulta sempre armato.

**Comment by lcavalli** [comment]
Io se armo/disarmo da tastiera o chiave vedo la corretta impostazione in HA. Dovresti verificare nel file yaml di aver impostato correttamente le variabili:
```yaml
# Global values
globals:
  # Arm home partitions (bitfield) as configured in alarm
  - id: armed_home
    type: uint8_t
    restore_value: no
    initial_value: '0x1'
  # Arm away partitions (bitfield) as configured in alarm
  - id: armed_away
    type: uint8_t
    restore_value: no
    initial_value: '0x3'
```
Ho scritto qualcosa in più su come vanno codificate nella issue #1.
Per far si che lo stato in HA sia sincronizzato devono essere codificate esattamente come nelle impostazioni dell'allarme, altrimenti il componente non è in grado di capire in che modalità si trova.
Il mapping è fatto qui:
```C++
if (alarmStatus != AlarmStatus::TRIGGERED) {
    // Parse armed partitions (away, stay and stay 0 delay modes are all armed)
    armed = (reply[0] | reply[1] | reply[2]) & partsList;

    // Parse disarmed partitions
    disarmed = reply[3] & partsList;

    // Publish alarm status
    if ((disarmed == partsList) && (alarmStatus != AlarmStatus::DISARMED)) {
        // All partitions are disarmed
        alarmStatusSensor->publish_state("disarmed");
        alarmStatus = AlarmStatus::DISARMED;
    } else if ((armed == (armed_home->value() & partsList)) && (alarmStatus != AlarmStatus::ARMED_HOME)) {
        // All partitions are armed home
        alarmStatusSensor->publish_state("armed_home");
        alarmStatus = AlarmStatus::ARMED_HOME;
    } else if ((armed == (armed_away->value() & partsList)) && (alarmStatus != AlarmStatus::ARMED_AWAY)) {
        // All partitions are armed away
        alarmStatusSensor->publish_state("armed_away");
        alarmStatus = AlarmStatus::ARMED_AWAY;
    }
}
```
