### ISSUE TITLE
Zone bypass switch

### ISSUE THREAD

**Issue by FAKKIUZ** [lcavalli/esp-kyo-alarm-generic#9]
Ciao Luca, a me interesserebbe avere lo switch per il bypass solo di alcune zone, invece con il codice seguente vengono abilitati gli switch delle zone in ordine numerico (zona 1, 2, 3,...) e non quelle che voglio io. 
Devo indicare qualcosa dopo lambda: come per i sensori binari?
Grazie.

```
# Zones bypass switch
- platform: custom
  id: zoneSwitches
  lambda: |-
    for(int i = 0; i < 32; i++) {
        auto s = new KyoZoneSwitch(i);
        App.register_component(s);
        ((KyoAlarmComponent*) kyo)->zoneSwitches.push_back(s);
    }
    return {((KyoAlarmComponent*) kyo)->zoneSwitches};
  switches:
    - id: kyo_zone4_sw
      name: "Tapparella portafinestra lavanderia"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone6_sw
      name: "Tapparella finestra bagnetto"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone8_sw
      name: "Tapparella portafinestra cucina"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone10_sw
      name: "Tapparella portafinestra camera"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone12_sw
      name: "Tapparella portafinestra cameretta"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone18_sw
      name: "Tapparella finestra sala"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone20_sw
      name: "Tapparella finestra bagno"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone22_sw
      name: "Tapparella finestra camera"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
```

**Comment by lcavalli** [comment]
Ciao!
Il codice di esempio crea 32 switch, uno per area e poi esporta i primi 4 verso HA. Per fare quello che vuoi tu puoi procedere in due modi:
1. Crei uno switch per ogni area, li esporti tutti verso HA e poi da HA presenti nella plancia solo quelli che ti servono, gli altri li disattivi
2. Cambi il codice e generi gli switch solo per le aree che ti servono (l'allarme parte a contare da 0). Non sono al PC e non posso provare, ma una cosa tipo questa dovrebbe funzionare:

```yaml
# Zones bypass switch
- platform: custom
  id: zoneSwitches
  lambda: |-
    auto s;
    s = new KyoZoneSwitch(3);
    App.register_component(s);
    ((KyoAlarmComponent*) kyo)->zoneSwitches.push_back(s);

    s = new KyoZoneSwitch(5);
    App.register_component(s);
    ((KyoAlarmComponent*) kyo)->zoneSwitches.push_back(s);

    s = new KyoZoneSwitch(7);
    App.register_component(s);
    ((KyoAlarmComponent*) kyo)->zoneSwitches.push_back(s);

    s = new KyoZoneSwitch(9);
    App.register_component(s);
    ((KyoAlarmComponent*) kyo)->zoneSwitches.push_back(s);

# e così via, oppure fai 2 cicli for con incremento di +2 da 3 a 11 e da 17 a 21

    return {((KyoAlarmComponent*) kyo)->zoneSwitches};
  switches:
    - id: kyo_zone4_sw
      name: "Tapparella portafinestra lavanderia"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone6_sw
      name: "Tapparella finestra bagnetto"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone8_sw
      name: "Tapparella portafinestra cucina"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone10_sw
      name: "Tapparella portafinestra camera"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone12_sw
      name: "Tapparella portafinestra cameretta"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone18_sw
      name: "Tapparella finestra sala"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone20_sw
      name: "Tapparella finestra bagno"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
    - id: kyo_zone22_sw
      name: "Tapparella finestra camera"
      icon: "mdi:leak"
      entity_category: "config"
      inverted: true
```
